apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common
    namespace: develop
    envs: 
    - ./common/.env
  - name: mg-cart
    namespace: develop
    envs:
    - ./mg-cart/.env
# Generator Option
generatorOptions:
  disableNameSuffixHash: true